spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TestTechDB
    username: postgres
    password: admin759
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
